
package de.matthias_ramsauer.itt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import net.java.dev.jaxb.array.ObjectFactory;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Party", targetNamespace = "http://itt.matthias_ramsauer.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Party {


    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://itt.matthias_ramsauer.de/Party/getGuestListRequest", output = "http://itt.matthias_ramsauer.de/Party/getGuestListResponse")
    public StringArray getGuestList();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://itt.matthias_ramsauer.de/Party/getDjRequest", output = "http://itt.matthias_ramsauer.de/Party/getDjResponse")
    public String getDj();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://itt.matthias_ramsauer.de/Party/inviteRequest", output = "http://itt.matthias_ramsauer.de/Party/inviteResponse")
    public boolean invite(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://itt.matthias_ramsauer.de/Party/amountOfGuestsRequest", output = "http://itt.matthias_ramsauer.de/Party/amountOfGuestsResponse")
    public int amountOfGuests();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://itt.matthias_ramsauer.de/Party/getDateRequest", output = "http://itt.matthias_ramsauer.de/Party/getDateResponse")
    public String getDate();

}
