
package de.matthias_ramsauer.itt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PartyService", targetNamespace = "http://itt.matthias_ramsauer.de/", wsdlLocation = "http://localhost:8080/party/0?wsdl")
public class PartyService
    extends Service
{

    private final static URL PARTYSERVICE_WSDL_LOCATION;
    private final static WebServiceException PARTYSERVICE_EXCEPTION;
    private final static QName PARTYSERVICE_QNAME = new QName("http://itt.matthias_ramsauer.de/", "PartyService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/party/0?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARTYSERVICE_WSDL_LOCATION = url;
        PARTYSERVICE_EXCEPTION = e;
    }

    public PartyService() {
        super(__getWsdlLocation(), PARTYSERVICE_QNAME);
    }

    public PartyService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARTYSERVICE_QNAME, features);
    }

    public PartyService(URL wsdlLocation) {
        super(wsdlLocation, PARTYSERVICE_QNAME);
    }

    public PartyService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARTYSERVICE_QNAME, features);
    }

    public PartyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartyService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Party
     */
    @WebEndpoint(name = "PartyPort")
    public Party getPartyPort() {
        return super.getPort(new QName("http://itt.matthias_ramsauer.de/", "PartyPort"), Party.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Party
     */
    @WebEndpoint(name = "PartyPort")
    public Party getPartyPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://itt.matthias_ramsauer.de/", "PartyPort"), Party.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARTYSERVICE_EXCEPTION!= null) {
            throw PARTYSERVICE_EXCEPTION;
        }
        return PARTYSERVICE_WSDL_LOCATION;
    }

}
